swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Simple Network Service API's
  contact:
    email: "yuv.swt@gmail.com"
basePath: "/"
tags:
  - name: "Ping"
  - name: "Resolve"
consumes:
  - "application/json"
produces:
  - "application/json"
# Paths supported by the server application
paths:
  /ping:
    get:
      tags:
        - "Ping"
      summary: "Http-ping health check."
      description: "Returns a ping."
      operationId: "controllers.ping_controller.ping"
      parameters: []
      responses:
        200:
          description: "Returns a ping response!"
  /resolve:
    get:
      tags:
        - "Resolve"
      summary: "Resolved lat and long to an address."
      description: "Returns an address."
      operationId: "controllers.resolve_controller.resolve"
      parameters:
        - name: lat
          in: query
          type: number
          format: float
          default: 49.45
        - name: long
          in: query
          type: number
          format: float
          default: -123.50
      responses:
        200:
          description: "Returns a human readable address"
